version: '3'
services:
  todoback:
    image: todobackend
    restart: always
    ports: 
      - 3000:3000
    networks:
      - todonetwork
  todofront:
    image: todofrontend
    restart: always
    environment:
      - REACT_API_HOST=todoback
    ports: 
      - 3001:3001
    depends_on:
      - todoback
    networks:
      - todonetwork
  todotests: 
    image: todotests
    restart: always
    environment:
      - FRONT-HOST=todofront
    depends_on:
      - todoback
      - todofront
    networks:
      - todonetwork

networks:
  todonetwork: